### ISSUE TITLE
Unable To Compile

### ISSUE THREAD

**Issue by bonedaddy** [uhthomas/pastry#1]
Unable to compile due to the following errors:
```
./pastry.go:128:27: too many arguments in call to n.Leafset.Insert
./pastry.go:128:28: undefined: k
./pastry.go:134:26: undefined: k
```

**Comment by uhthomas** [comment]
Hey!

Thanks for your interest in the project :) I've been super busy at work so it's never been finished, the handshake needs to be formalised and the routing tables need to be properly implemented before it would work. There's [another project (wendy) ](https://github.com/secondbit/wendy) which does something similar but with a proprietary API and hasn't been touched in over 7 years.  The main goal of this is to build the DHT on-top of QUIC and, similar to S/Kademlia, enforce cryptographic verification of nodes and messages at a protocol level. If you'd like to contribute then you're more than welcome! I'll be picking this up more actively in my free time so expect something workable within the next few weeks.

**Comment by bonedaddy** [comment]
Ah okay thats not a problem, I was digging through the commit history and thought it might've been due to an incorrect movement of code into the top level directory.

This seems like something I'd be willing to contribute on with some guidance. I took a look at the code causing the error i brought up in this issue, and I'm not quite sure what a fix would be.

**Comment by uhthomas** [comment]
I just committed a change which should make the code compilable, but I'm not pleased with it. There's a lot of unknowns with this project, but I think the most important thing right now is getting the routing tables, etc implemented. The final API and protocol are secondary to the core features.

There's a [PDF](https://freepastry.org/PAST/overview.pdf) on their website describing briefly how the DHT works and what factors come into play, it might be a good start to implement a generic routing table according to their specification?

I'm pretty busy this week but chances are I'll be working on this here and there, if there's anything that peaks your interest, or you have any suggestions then I'm all ears!

**Comment by bonedaddy** [comment]
Ok cool I'll poke around. Going to close this now
